fix(plugin): fn command load plugin core

diff --git a/commands/plugin/fn b/commands/plugin/fn
--- a/commands/plugin/fn
+++ b/commands/plugin/fn
@@ -17,6 +17,16 @@ core() {
   local fn=$2
   local args=${@:3}
 
+  if [ -z "$plugin_name" ]; then
+    log_error "[plugin][fn] plugin_name is required"
+    exit 1
+  fi
+
+  if [ -z "$fn" ]; then
+    log_error "[plugin][fn] fn_name is required"
+    exit 1
+  fi
+
   # @TODO
   set +e
 
diff --git a/core/plugin b/core/plugin
--- a/core/plugin
+++ b/core/plugin
@@ -179,45 +179,59 @@ plugin_list_bins() {
   fi
 }
 
+###
+plugin_load_configs() {
+  local plugin_name=$1
+  # file or dir
+  local config_path=$2
+
+  if [ -z "$plugin_name" ]; then
+    log_error "[$(timestamp)][plugin_run] plugin name is required"
+  fi
+
+  if [ "$(plugin_has $plugin_name)" = "false" ]; then
+    log_error "$plugin_name is not a valid plugin"
+    exit 1
+  fi
+
+  # ignore if not found
+  if [ ! -r $config_path ]; then
+    return
+  fi
+
+  # is config file
+  if [ -f $config_path ]; then
+    load_config_file $plugin_get_mod_path
+    return 
+  fi
+
+  # is config dir
+  local configs=$(ls $config_path)
+  for config in $configs; do
+    log_debug "[$(timestamp)][plugin_load_core][${plugin_name}] load: $config"
+    load_config_file $plugin_core_path/$config
+  done
+}
+
 plugin_load_mod() {
   local plugin_name=$1
   local plugin_get_mod_path=$(plugin_get_mod_path $plugin_name)
 
-  if [ -f $plugin_get_mod_path ]; then
-    load_config_file $plugin_get_mod_path
-  fi
+  plugin_load_configs $plugin_name $plugin_get_mod_path
 }
 
 plugin_load_core() {
-  local plugin_name=$1
+  local plugin_name=$1  
   local plugin_core_path=$(plugin_get_core_path $plugin_name)
-
-  # ignore if not found
-  if [ ! -d $plugin_core_path ]; then
-    return
-  fi
-
-  local utils=$(ls $plugin_core_path)
-  for util in $utils; do
-    log_debug "[$(timestamp)][plugin_load_core][${plugin_name}] load: $util"
-    load_config_file $plugin_core_path/$util
-  done
+  
+  plugin_load_configs $plugin_name $plugin_core_path
 }
 
 plugin_load_config() {
   local plugin_name=$1
   local plugin_config_path="$(plugin_get_config_path $plugin_name)"
 
-  # ignore if not found
-  if [ ! -d $plugin_config_path ]; then
-    return
-  fi
-
-  local configs=$(ls $plugin_config_path)
-  for config in $configs; do
-    log_debug "[$(timestamp)][plugin_load_core][${plugin_name}] load: $config"
-    load_config_file $plugin_config_path/$config
-  done
+  plugin_load_configs $plugin_name $plugin_config_path
 }
 
 plugin_load_override_config() {
@@ -227,16 +241,7 @@ plugin_load_override_config() {
   
   log_debug "[$(timestamp)][plugin_load_override_config][${plugin_name}] $plugin_overwrite_config_path"
 
-  # ignore if not found
-  if [ ! -d $plugin_overwrite_config_path ]; then
-    return
-  fi
-
-  local configs=$(ls $plugin_overwrite_config_path)
-  for config in $configs; do
-    log_debug "[$(timestamp)][plugin_load_override_config][${plugin_name}] load: $config"
-    load_config_file $plugin_overwrite_config_path/$config
-  done
+  plugin_load_configs $plugin_name $plugin_overwrite_config_path
 }
 
 plugin_load_parent_override_config() {
@@ -251,21 +256,7 @@ plugin_load_parent_override_config() {
     return
   fi
 
-  if [ -z "$plugin_name" ]; then
-    log_error "[$(timestamp)][plugin_load_parent_override_config] plugin name is required"
-    exit 1
-  fi
-
-  # ignore if not found
-  if [ ! -d $config_dir ]; then
-    return
-  fi
-
-  local configs=$(ls $config_dir)
-  for config in $configs; do
-    log_debug "[$(timestamp)][plugin_load_parent_override_config][${plugin_name}] load: $config"
-    load_config_file $config_dir/$config
-  done
+  plugin_load_configs $plugin_name $config_dir
 }
 
 plugin_get_version() {
@@ -361,6 +352,10 @@ plugin_run() {
   elif [ "$(array_first_element $plugin_command)" = "fn" ]; then
     # zmicro plugin run daemon fn daemon_list => zmicro plugin fn daemon daemon_list
     # zdaemon fn daemon_list => zmicro plugin fn daemon daemon_list
+    #
+    # load plugin core(utils)
+    plugin_load_core $plugin_name
+
     zmicro plugin fn $plugin_name ${plugin_command:2}
   else
     # load plugin core(utils)
@@ -390,6 +385,8 @@ export -f plugin_get_commands_path
 export -f plugin_exist
 export -f plugin_bin_exist
 export -f plugin_has
+
+export -f plugin_load_configs
 
 export -f plugin_load_mod
 export -f plugin_load_core
