chore: update for docker workspace

diff --git a/commands/config/timezone b/commands/config/timezone
--- a/commands/config/timezone
+++ b/commands/config/timezone
@@ -26,11 +26,17 @@ core() {
   # timedatectl list-timezones
 
   # Set timezone
-  sudo timedatectl set-timezone $timezone
-  if [ "$?" != "0" ]; then
-    log_error "Failed to set timezone: $timezone"
+  if [ "$(os_is_docker)" = "true" ]; then
+    # @TODO
+    # date >> /dev/null 2>&1
+    log_warn "@TODO set timezone in docker"
   else
-    log_success "Current timezone: $timezone"
+    sudo timedatectl set-timezone $timezone
+    if [ "$?" != "0" ]; then
+      log_error "Failed to set timezone: $timezone"
+    else
+      log_success "Current timezone: $timezone"
+    fi
   fi
 }
 
diff --git a/core/os b/core/os
--- a/core/os
+++ b/core/os
@@ -5,7 +5,19 @@ os_homedir() {
 }
 
 os_username() {
-  echo $USER
+  if [ "$USER" != "" ]; then
+    echo $USER
+    return
+  fi
+
+  local user=$(id -u -n)
+  if [ "$user" != "" ]; then
+    echo $user
+    return
+  fi
+
+  log_error "Cannot get user by os_username"
+  exit 1
 }
 
 os_shell() {
@@ -19,7 +31,6 @@ os_bash_profile() {
 os_zsh_profile() {
   echo "$HOME/.zshrc"
 }
-
 
 os_shell_profile() {
   if [ "$(os_is_zsh)" = "true" ]; then
@@ -190,6 +201,21 @@ os_is_federa() {
   fi
 }
 
+os_is_docker() {
+  if [ -f "/.dockerenv" ]; then
+    echo "true"
+    return
+  fi
+
+  cat /proc/self/cgroup | grep docker >> /dev/null 2>&1
+  if [ "$?" = "0" ]; then
+    echo "true"
+    return
+  fi
+  
+  echo "false"
+}
+
 os_top() {
   htop -t
 }
@@ -294,6 +320,8 @@ export -f os_is_ubuntu
 export -f os_is_alpine
 export -f os_is_archlinux
 export -f os_is_federa
+
+export -f os_is_docker
 
 export -f os_top
 export -f os_is_command_exist
diff --git a/core/plugin b/core/plugin
--- a/core/plugin
+++ b/core/plugin
@@ -76,11 +76,17 @@ plugin_register_all() {
     local bins=$(ls $plugin_path/$plugin/bin)
     for bin in $bins; do
       local bin_path=$ZMICRO_HOME/bin/$bin
+      local plugin_bin_path=$plugin_path/$plugin/bin/$bin
 
       if [ ! -f "$bin_path" ] && [ ! -x "$bin_path" ]; then
         log_debug "[$(timestamps)][plugin] register $plugin bin: $bin"
 
-        ln -s $plugin_path/$plugin/bin/$bin $ZMICRO_HOME/bin/$bin
+        set +e
+        ln -s $plugin_bin_path $bin_path
+        if [ "$?" != "0" ]; then
+          log_warn "[$(timestamps)][plugin] failed to register $plugin bin: $bin"
+        fi
+        set -e
       fi
     done
   done
