chore(core): export version::echo for plugins/service/...

diff --git a/core/config b/core/config
--- a/core/config
+++ b/core/config
@@ -63,24 +63,27 @@ config::load_dir() {
 }
 
 config::load_mod() {
+  local path=$1
+  local mod_path=$path/mod
+  if [ ! -f "$mod_path" ]; then
+    log::error "[config::load_mod] path is required"
+    exit 1
+  fi
+
+  config::load_file $mod_path
+
+  # @TODO REMOVE next version
   if [ -z $VERSION ]; then
-    log::error "VERSION is required"
+    log::error "[config::load_mod] VERSION is required"
     exit 1
   fi
 
   export ZMICRO_VERSION=$VERSION
   export ZMICRO_DESCRIPTION=$DESCRIPTION
-
-  # if [ -n $DEPENDENCIES ]; then
-  #   echo "load mod config found depdencies: $DEPENDENCIES"
-  #   array::each require $DEPENDENCIES
-  # fi
 }
 
 config::load_core_mod() {
-  config::load_file $ZMICRO_MOD
-
-  config::load_mod
+  config::load_mod $ZMICRO_HOME
 }
 
 config::load_user_config() {
diff --git a/core/plugin b/core/plugin
--- a/core/plugin
+++ b/core/plugin
@@ -295,6 +295,11 @@ plugin::load_mod() {
   local plugin_mod_path=$(plugin::get_mod_path $plugin_name)
 
   plugin::load_configs $plugin_name $plugin_mod_path
+
+  if [ -z "$VERSION" ]; then
+    log::error "[$(timestamp)][plugin::load_mod] VERSION is required in mod ($plugin_mod_path)"
+    exit 1
+  fi
 }
 
 plugin::load_core() {
diff --git a/core/version b/core/version
--- a/core/version
+++ b/core/version
@@ -15,24 +15,109 @@ version::update() {
 }
 
 version::timestamp() {
-  cd $ZMICRO_HOME
+  local path=$1
+  cd $path
+
   git show -s --format=%cd --date="format:%Y-%m-%d"
 }
 
 version::get() {
-  config::load_core_mod
+  local path=$1
+  cd $path
 
-  echo $ZMICRO_VERSION
+  config::load_mod $path
+
+  echo $VERSION
 }
 
 version::git_hash() {
-  cd $ZMICRO_HOME
+  local path=$1
+  cd $path
 
   git rev-parse --short=9 HEAD
+}
+
+version::echo() {
+  local path=$1
+  local version=$(version::get $path)
+  local git_hash=$(version::git_hash $path)
+  local timestamp=$(version::timestamp $path)
+
+  echo "$(color::green $version) (${git_hash} ${timestamp})"
+}
+
+version::main() {
+  version::echo $ZMICRO_HOME
+}
+
+version::plugin() {
+  local name=$1
+  if [ -z "$name" ]; then
+    log::error "[$(timestamp)][version::plugin] plugin name is required"
+    exit 1
+  fi
+
+  local path=$(plugin::get_path $name)
+  version::echo $path
+}
+
+version::package() {
+  local name=$1
+  if [ -z "$name" ]; then
+    log::error "[$(timestamp)][version::package] package name is required"
+    exit 1
+  fi
+
+  local path=$ZMICRO_HOME/plugins/package/packages/$name
+  if [ ! -d "$path" ]; then
+    log::error "[$(timestamp)][version::package] package(${name}) does not exist"
+    exit 1
+  fi
+
+  version::echo $path
+}
+
+version::service() {
+  local name=$1
+  if [ -z "$name" ]; then
+    log::error "[$(timestamp)][version::service] service name is required"
+    exit 1
+  fi
+
+  local path=$ZMICRO_HOME/plugins/service/services/$name
+  if [ ! -d "$path" ]; then
+    log::error "[$(timestamp)][version::service] service(${name}) does not exist"
+    exit 1
+  fi
+
+  version::echo $path
+}
+
+version::swarm() {
+  local name=$1
+  if [ -z "$name" ]; then
+    log::error "[$(timestamp)][version::swarm] swarm name is required"
+    exit 1
+  fi
+
+  local path=$ZMICRO_HOME/plugins/swarm/swarms/$name
+  if [ ! -d "$path" ]; then
+    log::error "[$(timestamp)][version::swarm] swarm(${name}) does not exist"
+    exit 1
+  fi
+
+  version::echo $path
 }
 
 export -f version::get
 export -f version::git_hash
 export -f version::timestamp
+
+export -f version::echo
+
+export -f version::main
+export -f version::plugin
+export -f version::service
+export -f version::swarm
 
 export -f version::update
