feat: support depdencies mode

diff --git a/core/config b/core/config
--- a/core/config
+++ b/core/config
@@ -24,7 +24,7 @@ load_config() {
     exit 1
   fi
 
-  load_mod_config
+  load_core_mod
 
   if [ -f $CONFIG_PATH ]; then
     load_config_file $CONFIG_PATH
@@ -53,11 +53,24 @@ load_config_dir() {
 }
 
 load_mod_config() {
-  load_config_file $ZMICRO_MOD
-  
-  # @TODO
+  if [ -z $VERSION ]; then
+    log_error "VERSION is required"
+    exit 1
+  fi
+
   export ZMICRO_VERSION=$VERSION
   export ZMICRO_DESCRIPTION=$DESCRIPTION
+
+  # if [ -n $DEPENDENCIES ]; then
+  #   echo "load mod config found depdencies: $DEPENDENCIES"
+  #   array_each require $DEPENDENCIES
+  # fi
+}
+
+load_core_mod() {
+  load_config_file $ZMICRO_MOD
+  
+  load_mod_config
 }
 
 load_user_config() {
@@ -119,6 +132,7 @@ export -f load_config_dir
 export -f load_config
 
 export -f load_mod_config
+export -f load_core_mod
 export -f load_user_config
 
 export -f zmicro_config_list
diff --git a/core/plugin b/core/plugin
--- a/core/plugin
+++ b/core/plugin
@@ -94,7 +94,17 @@ plugin_register_all() {
 
 plugin_path() {
   local plugin_name=$1
+  if [ -z $plugin_name ]; then
+    log_error "[plugin_path] plugin name is required"
+    exit 1
+  fi
+
   echo $ZMICRO_PLUGINS_PATH/$plugin_name
+}
+
+plugin_mod_path() {
+  local plugin_name=$1
+  echo $(plugin_path $plugin_name)/mod
 }
 
 plugin_bin_path() {
@@ -177,6 +187,7 @@ export -f plugin_list_bins
 export -f plugin_each
 
 export -f plugin_path
+export -f plugin_mod_path
 export -f plugin_bin_path
 export -f plugin_exist
 export -f plugin_bin_exist
