feat(core): add fs::prepend

diff --git a/core/fs b/core/fs
--- a/core/fs
+++ b/core/fs
@@ -97,6 +97,41 @@ fs::append() {
   fs::write $path $is_append_mode
 }
 
+fs::prepend() {
+  local path=$1
+  local text=$(</dev/stdin)
+
+  if [ -z "$path" ] || [ -z "$text" ]; then
+    log::error "[$(timestamp)][fs::write] path and text is required"
+    exit 1
+  fi
+
+  if [ ! -f $path ]; then
+    log::error "[$(timestamp)][fs::write] path $path not found"
+    exit 1
+  fi
+
+  local origin_text=$(fs::read $path)
+
+  # echo "origin_text: $origin_text"
+  # echo "text: $text"
+
+  # no permission
+  # try to use sudo/root
+  if [ ! -w $path ]; then
+    sudo tee $path >>/dev/null <<EOF
+${text}
+${origin_text}
+EOF
+    return
+  fi
+
+  cat <<EOF >$path
+${text}
+${origin_text}
+EOF
+}
+
 fs::remove_empty_line() {
   local file_path=$1
   local tmp_file_path=$(os::tmp_file)
@@ -186,6 +221,7 @@ export -f fs::write
 export -f fs::read
 
 export -f fs::append
+export -f fs::prepend
 
 export -f fs::remove_line_has_str
 export -f fs::remove_empty_line
