feat(update): add update lock in 5 minutes

diff --git a/core/log b/core/log
--- a/core/log
+++ b/core/log
@@ -150,6 +150,20 @@ log_version() {
   fi
 }
 
+log_plugin_update_lock() {
+  # format: plugin_name#timestamps
+  # example: daemon#timestamps
+  if [ -z "$plugin_name" ]; then
+    log_error "[log_plugin_update_lock] plugin_name is required"
+    exit 1
+  fi
+
+  local msg="$plugin_name#$(timestamp)"
+  # sed -i "/^\s*$/d" $ZMICRO_LOCK_UPDATE_PATH
+  
+  # @TODO @TODO @TODO
+}
+
 export -f log_init
 
 export -f log
@@ -164,3 +178,5 @@ export -f log_timestamp
 export -f log_command
 export -f log_update
 export -f log_version
+
+export -f log_plugin_update_lock
diff --git a/core/timestamp b/core/timestamp
--- a/core/timestamp
+++ b/core/timestamp
@@ -5,4 +5,80 @@ timestamp() {
   echo $res
 }
 
+timestamp_to_seconds() {
+  local text=$@
+  if [ -z "$text" ]; then
+    log_error "[timestamp_to_seconds] timestamp string is required"
+    exit 1
+  fi
+
+  date -d "$text" +%s
+}
+
+timestamp_gt() {
+  local a=$1
+  local b=$2
+
+  echo "a: $a"
+  echo "b: $b"
+
+  if [ $a -gt $b ]; then
+    echo "true"
+  else
+    echo "false"
+  fi
+}
+
+timestamp_lt() {
+  local a=$1
+  local b=$2
+
+  if [ $a -lt $b ]; then
+    echo "true"
+  else
+    echo "false"
+  fi
+}
+
+# in x minutes
+# example: 5 2021-09-05 11:30:10
+# example: 5 1630824627
+timestamp_in_x_minutes() {
+  local x_minutes=$1
+  local text=${@:2}
+
+  if [ -z "$x_minutes" ]; then
+    log_error "[timestamp_recently] x_minutes is required"
+    exit 1
+  fi
+
+  if [ -z "$text" ]; then
+    log_error "[timestamp_recently] timestamp string | numver is required"
+    exit 1
+  fi
+
+  local x_seconds=$((60 * $x_minutes))
+  local ts=$text
+
+  echo $text | grep ":" >> /dev/null 2>&1
+  if [ "$?" = "0" ]; then
+    ts=$(timestamp_to_seconds $text)
+  fi
+
+  local now=$(date +%s)
+  local ts_5m_later=$(($ts + $x_seconds))
+
+  timestamp_lt $now $ts_5m_later
+}
+
+# in 5 minutes
+timestamp_recently() {
+  timestamp_in_x_minutes 5 $@
+}
+
 export -f timestamp
+export -f timestamp_to_seconds
+export -f timestamp_gt
+export -f timestamp_lt
+export -f timestamp_in_x_minutes
+export -f timestamp_recently
