fix: apply proxy nc unrecognize hostname

diff --git a/core/net b/core/net
--- a/core/net
+++ b/core/net
@@ -26,6 +26,73 @@ net::is_in_china() {
   fi
 }
 
+net::is_ip() {
+  os::is_ip $1
+}
+
+net::get_domain_ip() {
+  local domain=$1
+  if [ -z "$domain" ]; then
+    log::error "domain is required"
+    exit 1
+  fi
+
+  dig +short $domain @114.114.114.114
+}
+
+net::is_url_visitable() {
+  local url=$1
+  if [ -z "$url" ]; then
+    log::error "url is required"
+    return
+  fi
+
+  curl -I $1 --connect-timeout 3 >>/dev/null 2>&1
+  if [ "$?" != "0" ]; then
+    echo "false"
+  else
+    echo "true"
+  fi
+}
+
+net::is_port_visitable() {
+  local ip=$1
+  local port=$2
+
+  if [ -z "$ip" ]; then
+    log::error "ip is required"
+    exit 1
+  fi
+
+  if [ -z "$port" ]; then
+    log::error "port is required"
+    exit 1
+  fi
+
+  # no a valid ip, search dns
+  if [ "$(net::is_ip $ip)" = "false" ]; then
+    ip=$(net::get_domain_ip $ip)
+  fi
+
+  if [ "$(os::has_command nc)" = "true" ]; then
+    nc -z -v -n -w 1 $ip $port >>/dev/null 2>&1
+    if [ "$?" != "0" ]; then
+      echo "false"
+    else
+      echo "true"
+    fi
+  else
+    # @TODO
+    echo "true"
+  fi
+}
+
 export -f net::is_in_china
 export -f net::is_github_visitable
 export -f net::is_google_visitable
+
+export -f net::is_ip
+export -f net::get_domain_ip
+
+export -f net::is_url_visitable
+export -f net::is_port_visitable
diff --git a/core/os b/core/os
--- a/core/os
+++ b/core/os
@@ -248,6 +248,30 @@ os::is_support_color() {
   fi
 }
 
+os::is_ip() {
+  local ip=$1
+
+  if [ -z "$ip" ]; then
+    log::error "ip is required"
+    return
+  fi
+
+  # regexp syntax: [[ a =~ b ]]
+  # if [[ "1.2.3.4" =~ "^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$" ]]; then
+  #   echo "true"
+  # else
+  #   echo "false"
+  # fi
+
+  # is ip
+  echo $ip | grep -E "^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$" >>/dev/null 2>&1
+  if [ "$?" = "0" ]; then
+    echo "true"
+  else
+    echo "false"
+  fi
+}
+
 os::device_config() {
   local cpus=$(cat /proc/cpuinfo | grep processor | wc -l)
   local memory=$(((($(cat /proc/meminfo | grep MemTotal | awk '{print $2}') / 1024 / 1024)) + 1))
@@ -457,7 +481,7 @@ os::random_string() {
   fi
 
   if [ "$(os::is_command_exist openssl)" = "false" ]; then
-    cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $length | head -n 1 
+    cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $length | head -n 1
     return
   fi
 
@@ -476,7 +500,7 @@ os::random_int() {
     min=0
   fi
 
-  echo $(( ( RANDOM % $max )  + $min ))
+  echo $(((RANDOM % $max) + $min))
 }
 
 os::random_id() {
@@ -626,7 +650,7 @@ os::inquirer() {
   fi
 
   if [ "$type" = "text" ]; then
-    inquirer::text "$description" value "" "value is required" inquirer::required 
+    inquirer::text "$description" value "" "value is required" inquirer::required
   elif [ "$type" = "yesno" ]; then
     local choices=("Yes" "No")
     inquirer::select "$description" choices value
@@ -635,7 +659,7 @@ os::inquirer() {
     else
       value="false"
     fi
-  else 
+  else
     log::error "[os::inquirer] invalid type($type), options: text, yesno"
     exit 1
   fi
@@ -728,7 +752,7 @@ os::is_nodejs_installed() {
   export NODE_USER_HOME=$HOME/.node
   export PATH=$NODE_HOME/bin:$NODE_USER_HOME/bin:$PATH
 
-  which node >> /dev/null 2>&1
+  which node >>/dev/null 2>&1
   if [ "$?" = "0" ]; then
     echo "true"
   else
@@ -742,7 +766,7 @@ os::is_go_installed() {
   export GOPATH=$HOME/.go
   export PATH=$GOHOME/bin:$GOPATH/bin:$PATH
 
-  which go >> /dev/null 2>&1
+  which go >>/dev/null 2>&1
   if [ "$?" = "0" ]; then
     echo "true"
   else
@@ -756,7 +780,7 @@ os::is_deno_installed() {
   export DENO_USER_HOME=$HOME/.deno
   export PATH=$DENO_HOME/bin:$DENO_USER_HOME/bin:$PATH
 
-  which deno >> /dev/null 2>&1
+  which deno >>/dev/null 2>&1
   if [ "$?" = "0" ]; then
     echo "true"
   else
@@ -770,7 +794,7 @@ os::is_rust_installed() {
   export RUST_USER_HOME=$HOME/.rust
   export PATH=$RUST_HOME/rustc/bin:$RUST_HOME/cargo/bin:$RUST_USER_HOME/bin:$PATH
 
-  which rustc >> /dev/null 2>&1
+  which rustc >>/dev/null 2>&1
   if [ "$?" = "0" ]; then
     echo "true"
   else
@@ -864,3 +888,5 @@ export -f os::is_nodejs_installed
 export -f os::is_go_installed
 export -f os::is_deno_installed
 export -f os::is_rust_installed
+
+export -f os::is_ip
