chore(core): type add strings::contains, alias of string::has

diff --git a/core/type b/core/type
--- a/core/type
+++ b/core/type
@@ -162,6 +162,23 @@ string::has() {
     exit 1
   fi
 
+  strings::contains "$text" "$sub"
+}
+
+strings::contains() {
+  local text=$1
+  local sub=$2
+
+  if [ "$sub" = "" ]; then
+    log::error "[strings::contains] sub is required"
+    exit 1
+  fi
+
+  if [ "$text" = "" ]; then
+    log::error "[strings::contains] text is required"
+    exit 1
+  fi
+
   string::match "$text" "$sub"
 }
 
@@ -415,6 +432,7 @@ export -f string::replace
 export -f string::remove
 export -f string::match
 export -f string::has
+export -f strings::contains
 export -f strings::equals # compatible
 export -f string::equals
 export -f string::first_char
