feat(machine): add lvm ls

diff --git a/commands/machine/lvm/remove b/commands/machine/lvm/remove
--- a/commands/machine/lvm/remove
+++ b/commands/machine/lvm/remove
@@ -12,6 +12,17 @@ is_lvm_created() {
   echo "true"
 }
 
+is_device() {
+  local device=$1
+  echo $device | grep "^/dev/" >> /dev/null 2>&1
+  if [ "$?" = "0" ]; then
+    echo "true"
+    return
+  fi
+
+  echo "false"
+}
+
 remove() {
   local device=$1
   # /dev/sda => sda
@@ -22,7 +33,7 @@ remove() {
     exit 1
   fi
 
-  if [ "$deviceName" = "" ]; then
+  if [ "$(is_device $device)" = "false" ]; then
     log_error "device should start with /dev/*, but found: ${device}"
     exit 1
   fi
@@ -30,7 +41,7 @@ remove() {
   # 1.initial physical volume
   sudo pvs | grep $device >> /dev/null 2>&1
   if [ "$?" != "0" ]; then
-    log_success "lvm device not found, maybe removed before"
+    log_success "lvm device(${device}) not found, maybe removed before"
     exit 0
   fi
 
