feat(code): support zmicro project code zcorky/zmicro

diff --git a/commands/_internal/code b/commands/_internal/code
--- a/commands/_internal/code
+++ b/commands/_internal/code
@@ -189,6 +189,64 @@ core() {
     cd $path
     code .
     ;;
+  project)
+    local path=$HOME/code
+
+    if [ -z "$name" ]; then
+      log::error "project name is required"
+      exit 1
+    fi
+
+    # if name is not a string contains one '/'        => throw error
+    # if name = zcorky/zmicro                         => path=$HOME/code/github.com/zcorky/zmicro
+    # if name = github.com/zcorky/zmicro              => path=$HOME/code/github.com/zcorky/zmicro
+    # if name = https://github.com/zcorky/zmicro      => path=$HOME/code/github.com/zcorky/zmicro
+    # if name = https://github.com/zcorky/zmicro.git  => path=$HOME/code/github.com/zcorky/zmicro
+    # if name = http://git.zcorky.com/zcorky/zmicro   => path=$HOME/code/git.zcorky.com/zcorky/zmicro
+
+    # remove https:// or http://
+    if [[ $name == "http"* ]] || [[ $name == "https"* ]]; then
+      name=$(echo $name | sed 's/https\?:\/\///g')
+    fi
+
+    # remove .git
+    if [[ $name == *".git" ]]; then
+      name=$(echo $name | sed 's/\.git//g')
+    fi
+
+    # if name contains one '/' => add github.com
+    if [[ $name == *"/"* ]]; then
+      name=github.com/$name
+    fi
+
+    # check if name contains two '/'
+    if [[ $name != *"/"*"/"* ]]; then
+      log::error "project name($name) is invalid"
+      exit 1
+    fi
+
+    path=$path/$name
+
+    if [ ! -d $path ]; then
+      # log::error "${where}(${name}) not found"
+      # exit 1
+
+      log::info "${where}(${name}) not found, downloading ..."
+      zmicro project add $name
+      if [ "$?" != "0" ]; then
+        log::error "project (${name}) download failed"
+        exit 1
+      fi
+    fi
+
+    if [ ! -d $path ]; then
+      log::error "project(${where}) not found (2)"
+      exit 1
+    fi
+
+    cd $path
+    code .
+    ;;
   *)
     # fallback to plugin
     name=$where
