chore: code support template

diff --git a/commands/_internal/code b/commands/_internal/code
--- a/commands/_internal/code
+++ b/commands/_internal/code
@@ -94,6 +94,24 @@ core() {
     cd $path
     code .
     ;;
+  template)
+    local path=$ZMICRO_HOME/plugins/${where}
+    if [ ! -d $path ]; then
+      log::error "template(${where}) not found (2)"
+      exit 1
+    fi
+
+    if [ -n "$name" ]; then
+      path=$path/${where}s/$name
+    fi
+    if [ ! -d $path ]; then
+      log::error "${where}(${name}) not found"
+      exit 1
+    fi
+
+    cd $path
+    code .
+    ;;
   *)
     # fallback to plugin
     name=$where
