chore: remove invalid source env

diff --git a/commands/_internal/go b/commands/_internal/go
--- a/commands/_internal/go
+++ b/commands/_internal/go
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-. $ZMICRO_HOME/core/env
-
 help() {
   echo "Usage:"
   echo "  zmicro go <where>"
@@ -31,79 +29,79 @@ core() {
   # echo "name: $name"
 
   case $where in
-    home)
-      cd $ZMICRO_HOME
-      exec $SHELL
-      ;;
-    plugin)
-      if [ -z "$name" ]; then
-        log::error "plugin name is required"
-        exit 1
-      fi
+  home)
+    cd $ZMICRO_HOME
+    exec $SHELL
+    ;;
+  plugin)
+    if [ -z "$name" ]; then
+      log::error "plugin name is required"
+      exit 1
+    fi
 
-      local plugin_path=$ZMICRO_HOME/plugins/$name
-      if [ ! -d $plugin_path ]; then
-        log::error "plugin (${name}) not found"
-        exit 1
-      fi
+    local plugin_path=$ZMICRO_HOME/plugins/$name
+    if [ ! -d $plugin_path ]; then
+      log::error "plugin (${name}) not found"
+      exit 1
+    fi
 
-      cd $plugin_path
-      exec $SHELL
-      ;;
-    service)
-      local path=$ZMICRO_HOME/plugins/${where}
-      if [ ! -d $path ]; then
-        log::error "plugin(${where}) not found (1)"
-        exit 1
-      fi
+    cd $plugin_path
+    exec $SHELL
+    ;;
+  service)
+    local path=$ZMICRO_HOME/plugins/${where}
+    if [ ! -d $path ]; then
+      log::error "plugin(${where}) not found (1)"
+      exit 1
+    fi
 
-      if [ -n "$name" ]; then
-        path=$path/${where}s/$name        
-      fi
-      if [ ! -d $path ]; then
-        log::error "${where}(${name}) not found"
-        exit 1
-      fi
+    if [ -n "$name" ]; then
+      path=$path/${where}s/$name
+    fi
+    if [ ! -d $path ]; then
+      log::error "${where}(${name}) not found"
+      exit 1
+    fi
 
-      cd $path
-      exec $SHELL
-      ;;
-    package)
-      local path=$ZMICRO_HOME/plugins/${where}
-      if [ ! -d $path ]; then
-        log::error "package(${where}) not found (2)"
-        exit 1
-      fi
+    cd $path
+    exec $SHELL
+    ;;
+  package)
+    local path=$ZMICRO_HOME/plugins/${where}
+    if [ ! -d $path ]; then
+      log::error "package(${where}) not found (2)"
+      exit 1
+    fi
 
-      if [ -n "$name" ]; then
-        path=$path/${where}s/$name        
-      fi
-      if [ ! -d $path ]; then
-        log::error "${where}(${name}) not found"
-        exit 1
-      fi
+    if [ -n "$name" ]; then
+      path=$path/${where}s/$name
+    fi
+    if [ ! -d $path ]; then
+      log::error "${where}(${name}) not found"
+      exit 1
+    fi
 
-      cd $path
-      exec $SHELL
-      ;;
-    *)
-      # fallback to plugin
-      name=$where
-      
-      if [ -z "$name" ]; then
-        log::error "plugin name is required"
-        exit 1
-      fi
+    cd $path
+    exec $SHELL
+    ;;
+  *)
+    # fallback to plugin
+    name=$where
 
-      local plugin_path=$ZMICRO_HOME/plugins/$name
-      if [ ! -d $plugin_path ]; then
-        log::error "plugin (${name}) not found (3)"
-        exit 1
-      fi
+    if [ -z "$name" ]; then
+      log::error "plugin name is required"
+      exit 1
+    fi
 
-      cd $plugin_path
-      exec $SHELL
-      ;;
+    local plugin_path=$ZMICRO_HOME/plugins/$name
+    if [ ! -d $plugin_path ]; then
+      log::error "plugin (${name}) not found (3)"
+      exit 1
+    fi
+
+    cd $plugin_path
+    exec $SHELL
+    ;;
   esac
 }
 
