feat(core): add install/reinstall [self | plugin]

diff --git a/commands/_internal/initialize b/commands/_internal/initialize
--- a/commands/_internal/initialize
+++ b/commands/_internal/initialize
@@ -2,17 +2,17 @@
 
 set -e
 
-clone_git() {
+initialize_repo() {
   # install
   if [ ! -d $ZMICRO_HOME ]; then
     git clone $ZMICRO_GIT -b $ZMICRO_VERSION $ZMICRO_HOME
     # git clone $ZMICRO_GIT -b master $ZMICRO_HOME
-  else
-    log_info "[initailize] installed before, if you want to update, run 'zmicro update'"
+  # else
+  #   log_info "[initailize] installed before, if you want to update, run 'zmicro update'"
   fi
 }
 
-init() {
+initialize_config() {
   PATH=$ZMICRO_BIN_PATH:$PATH
   zmicro config rc
 
@@ -30,11 +30,65 @@ init() {
 
   # $ZMICRO_BIN_PATH/zmicro config git $USER $USER"@local"
   zmicro config git # $GIT_USERNAME $GIT_EMAIL
-
-  clone_git
-
-  # install dependency plugins ...
-  require_core_mod
 }
 
-init
+initialize_depdendencies() {
+  # install dependency plugins ...
+  require_core_mod $@
+}
+
+help() {
+  echo "update zmicro"
+  echo ""
+  echo "Usage:"
+  echo "  zmicro update [...options]"
+  echo "    -p, --plugin <plugin_name | all>    Update all or one plugin"
+  echo "    -a, --all   Update core and all plugins"
+}
+
+core() {
+  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+    help
+    exit 0
+  fi
+
+  while [[ $# -gt 0 ]]; do
+    local key=$1
+    local value=$2
+    case $key in
+      -h | --help)
+        help
+        exit 0
+        ;;
+      -u | --update)
+        set_var is_plugin_update true
+        shift
+        ;;
+      *)
+        if [ "$(string_match $key ^-)" = "true" ]; then
+          echo "ERROR: unknown parameter \"$key\""
+          help
+          exit 1
+        fi
+
+        shift
+        ;;
+    esac
+  done
+
+  initialize_repo
+  initialize_config
+
+  if [ "$is_plugin_update" = "true" ]; then
+    initialize_depdendencies -u
+  else
+    initialize_depdendencies
+  fi
+}
+
+run() {
+  core $@
+}
+
+run $@
+
diff --git a/core/require b/core/require
--- a/core/require
+++ b/core/require
@@ -4,21 +4,28 @@ require() {
   local plugin_name=$1
   local plugin_version=$2
   local plugin_repo=$3
+  local force_update=$IS_REQUIRE_MOD_UPDATE_TMP_GLOBAL
 
-  if [ "$(zmicro plugin has $plugin_name)" = "false" ]; then
-    log_info "[require] installing: ${plugin_name} ..."
-    
-    # @TODO
-    zmicro plugin install $plugin_name $plugin_version $plugin_repo
-    if [ "$?" = "0" ]; then
-      log_success "[require] install success: ${plugin_name}"
-    else
-      log_error "[require] install failed: ${plugin_name}"
+  if [ "$(zmicro plugin has $plugin_name)" = "true" ]; then
+    log_debug "[$(timestamp)][require] installed before: ${plugin_name}"
+
+    if [ "$force_update" = "true" ]; then
+      log_info "[$(timestamp)][require] update: ${plugin_name}"
+      zmicro plugin update $plugin_name
     fi
-  else
-    log_success "[require] installed before: ${plugin_name}"
+    return
   fi
 
+  log_info "[$(timestamp)][require] install: $plugin_name ($plugin_version) ..."
+  
+  # @TODO
+  zmicro plugin install $plugin_name $plugin_version $plugin_repo
+  if [ "$?" = "0" ]; then
+    log_success "[$(timestamp)][require] install success: ${plugin_name}"
+  else
+    log_error "[$(timestamp)][require] install failed: ${plugin_name}"
+  fi
+    
   sleep 1
 }
 
@@ -27,23 +34,52 @@ require_parse() {
   # compose@v0.0.1
   local text=$2
 
+  # echo "IS_REQUIRE_MOD_UPDATE_TMP_GLOBAL: $IS_REQUIRE_MOD_UPDATE_TMP_GLOBAL"
+  # echo "is_require_mod_update: $is_require_mod_update"
+
   local plugin_name=$(echo $text | awk -F '@' '{print $1}')
   local plugin_version=$(echo $text | awk -F '@' '{print $2}' | awk -F '#' '{print $1}')
   local plugin_repo=$(echo $text | awk -F '#' '{print $2}')
 
   # echo "[require_parse] ${plugin_name}(${plugin_version}) - ${plugin_repo}"
-  log_info "[require] install plugin $plugin_name ($plugin_version) ..."
+  # log_info "[$(timestamp)][require] install plugin $plugin_name ($plugin_version) ..."
   require $plugin_name $plugin_version $plugin_repo
 }
 
 require_mod() {
-  # @TODO overide core DEPENDENCIES
+    # @TODO overide core DEPENDENCIES
   if [ -n ${DEPENDENCIES} ]; then
     # echo "overide DEPENDENCIES"
     DEPENDENCIES=()
   fi
 
   local mod_path=$1
+  local is_require_mod_update=false
+
+  shift
+  while [[ $# -gt 0 ]]; do
+    local key=$1
+    local value=$2
+    case $key in
+      -u | --update)
+        set_var is_require_mod_update true
+        shift
+        ;;
+      *)
+        if [ "$(string_match $key ^-)" = "true" ]; then
+          log_error "[require_mod] ERROR: unknown parameter \"$key\""
+          exit 1
+        fi
+
+        shift
+        ;;
+    esac
+  done
+
+  # @TODO cannot pass params in array_each, so use global instead of
+  IS_REQUIRE_MOD_UPDATE_TMP_GLOBAL=$is_require_mod_update
+
+  # load mod
   load_config_file $mod_path
 
   if [ -n $DEPENDENCIES ]; then
@@ -52,7 +88,7 @@ require_mod() {
       return
     fi
 
-    log_info "[require] found depdencies: ${dependeny_count} ..."
+    log_info "[$(timestamp)][require] found depdencies: ${dependeny_count} ..."
 
     array_each require_parse ${DEPENDENCIES[@]}
 
@@ -67,7 +103,7 @@ require_mod() {
 }
 
 require_core_mod() {
-  require_mod $ZMICRO_MOD
+  require_mod $ZMICRO_MOD $@
 }
 
 require_plugin_mod() {
@@ -79,7 +115,7 @@ require_plugin_mod() {
 
   # echo "plugin_name: $(plugin_mod_path $plugin_name)"
   # echo "${DEPENDENCIES[@]}"
-  require_mod $(plugin_mod_path $plugin_name)
+  require_mod $(plugin_mod_path $plugin_name) $@
 }
 
 export -f require
