feat(release): support current branch, not fixed master

diff --git a/commands/_internal/release b/commands/_internal/release
--- a/commands/_internal/release
+++ b/commands/_internal/release
@@ -39,6 +39,7 @@ core() {
 
   local origin_version=$(version::zmicro)
   local default_new_version=$(version::next $origin_version)
+  local tmp_error_log=$(os::tmp_file)
 
   local is_valid="false"
   while [ "$is_valid" = "false" ]; do
@@ -66,11 +67,28 @@ core() {
   git pull origin master
   git add mod
   git commit -m "chore(release): bumped version to ${new_version}"
-  git tag ${new_version}
-  git push origin ${new_version}
-  git push origin master
+  git tag ${new_version} -f
 
-  log::success "[release] ${plugin_name} ${new_version}"
+  log::info "[$(timestamp)] pushing version to tag: ${new_version} ..."
+  git push origin ${new_version} -f >>/dev/null 2>$tmp_error_log
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)] failed to release ${new_version}: push tag error"
+    cat $tmp_error_log
+    return 1
+  fi
+
+  local current_branch=$(git::branch)
+  log::info "[$(timestamp)] pushing version to branch: ${current_branch} ..."
+  git push origin $current_branch
+  git push origin ${current_branch} >>/dev/null 2>$tmp_error_log
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)] failed to release ${new_version}: push master error"
+    cat $tmp_error_log
+    return 1
+  fi
+
+  log::info "[$(timestamp)] repository: $(git::repo_url)"
+  log::success "[$(timestamp)] succeed to release($(color::green ${plugin_name})): $(color::green ${new_version})"
 }
 
 run() {
